CREATE TABLE IF NOT EXISTS firm_imap_settings (
    firm_id INTEGER PRIMARY KEY REFERENCES firms(id) ON DELETE CASCADE,
    host VARCHAR(255) NOT NULL,
    port INTEGER NOT NULL DEFAULT 993 CHECK (port BETWEEN 1 AND 65535),
    username VARCHAR(255) NOT NULL,
    password_encrypted TEXT NOT NULL,
    use_tls BOOLEAN NOT NULL DEFAULT true,
    mailbox VARCHAR(255) NOT NULL DEFAULT 'INBOX',
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
